const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts), 'utf8')
const bytes = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts))

test('new tab composes its masthead from the meteor and a Necosmic wordmark', () => {
  const html = read('src', 'renderer', 'pages', 'newtab.html')
  const protocol = read('src', 'main', 'protocol.js')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  assert.match(html, /id="ember-brand"/)
  assert.match(html, /href="\/theme\.css"/)
  assert.match(protocol, /\['\/theme\.css', path\.join\(RENDERER, 'theme\.css'\)\]/)
  assert.match(html, /\/brand\.js/)
  assert.match(html, /\/brand\.css/)
  assert.match(protocol, /Necosmic-PersonalUse\.otf/)
  assert.match(css, /@font-face/)
  assert.match(css, /font-family:\s*'Necosmic'/)
  assert.match(css, /\.ember-wordmark[\s\S]+color:\s*#fff/)
  assert.match(css, /\.ember-meteor[\s\S]+filter:\s*drop-shadow/)
  const wordmarkRule = css.match(/\.ember-wordmark\s*\{([^}]*)\}/)?.[1] || ''
  assert.doesNotMatch(wordmarkRule, /filter\s*:/)
})

test('new tab keeps Ember content above configurable native double-blur layers', () => {
  const html = read('src', 'renderer', 'pages', 'newtab.html')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  const js = read('src', 'renderer', 'pages', 'liquid-glass-search.js')
  const main = read('src', 'main', 'index.js')
  assert.match(html, /class="native-glass-page"/)
  assert.match(html, /liquid-glass-search\.js/)
  assert.match(html, /id="native-liquid-glass"/)
  assert.match(js, /nativeGlass\?\.getSettings/)
  assert.match(js, /Promise\.resolve/)
  assert.match(js, /glass__warp/)
  assert.match(js, /feDisplacementMap/)
  assert.match(js, /calculateDirectionalScale/)
  assert.match(css, /html,\s*body\s*\{[^}]*background:\s*transparent/)
  assert.doesNotMatch(css, /\.search\s*\{/)
  assert.match(css, /\.liquid-glass-search[\s\S]+background:\s*transparent/)
  assert.match(css, /\.liquid-glass-search[\s\S]+border:\s*0/)
  assert.match(css, /\.liquid-glass-search input:focus[\s\S]+outline:\s*0\s*!important/)
  assert.match(css, /\.liquid-glass-search input:focus[\s\S]+box-shadow:\s*none\s*!important/)
  // The window is opaque with a system backdrop rather than layered. A
  // transparent window is excluded from Snap, Snap Layouts and the minimise
  // and restore animations, and has to draw its own corner — which is what
  // left a square black one behind Ember's rounded one.
  assert.match(main, /transparent:\s*false/)
  assert.match(main, /backgroundMaterial:\s*'acrylic'/)
  assert.match(main, /roundedCorners:\s*true/)
  assert.match(main, /backgroundColor:\s*'#00000000'/)
})

test('browser chrome provides a compact live bookmarks bar', () => {
  const html = read('src', 'renderer', 'chrome.html')
  assert.match(html, /id="bookmarks-bar"/)
  assert.match(html, /id="bookmarks-items"/)
  assert.match(html, /id="import-bookmarks"/)
})

test('browser chrome is one unified Ember shell rather than the old permanent toolbar', () => {
  const html = read('src', 'renderer', 'chrome.html')
  const css = read('src', 'renderer', 'chrome.css')
  const material = read('src', 'renderer', 'shell-material.css')
  const js = read('src', 'renderer', 'chrome.js')
  const preload = read('src', 'renderer', 'preload.js')

  for (const id of ['sidebar-toggle', 'top-chrome', 'top-navigation', 'tabstrip', 'ext-btn', 'win-min', 'win-max', 'win-close']) {
    assert.match(html, new RegExp(`id="${id}"`), id)
  }
  assert.doesNotMatch(html, /class="toolbar"/)
  assert.doesNotMatch(html, /id="bookmarks-toggle"/)
  assert.match(js, /window\.ember\.minimize\(\)/)
  assert.match(js, /window\.ember\.maximize\(\)/)
  assert.match(js, /window\.ember\.close\(\)/)
  assert.match(html, /class="omnibox omnibox-transient"/, 'Ctrl+L survives as a transient surface')

  for (const token of ['--sidebar-width', '--topbar-height', '--tab-height', '--tab-max-width', '--tab-min-width', '--ember-orange']) {
    assert.match(css, new RegExp(token))
  }
  for (const token of ['--outer-radius', '--content-radius', '--frame-inset']) {
    assert.match(material, new RegExp(token))
  }
  assert.match(material, /radial-gradient[\s\S]+linear-gradient/, 'shell uses one smouldering compound gradient')
  assert.doesNotMatch(html, /shell-outline/, 'shell has no segmented orange outline overlay')
  assert.doesNotMatch(css, /\.shell-outline/, 'shell has no segmented orange outline styling')
  assert.match(css, /-webkit-app-region:\s*no-drag/)
  assert.match(css, /(?:^|[;{])\s*app-region:\s*no-drag/m)
  assert.match(js, /pointerdown/)
  assert.match(js, /beginWindowDrag/)
  assert.match(js, /updateWindowDrag/)
  assert.match(js, /endWindowDrag/)
  assert.doesNotMatch(js, /NON_DRAG_SELECTOR[^\n]*\.tabstrip/, 'blank tab-strip gaps remain draggable')
  assert.doesNotMatch(js, /NON_DRAG_SELECTOR[^\n]*\.top-navigation/, 'blank navigation gaps remain draggable')
  assert.doesNotMatch(js, /NON_DRAG_SELECTOR[^\n]*\.top-actions/, 'blank action gaps remain draggable')
  assert.match(preload, /WIN_DRAG_START/)
  assert.match(js, /getChromeConfig/)
  assert.match(js, /setSidebarOpen/)
})

test('Favorite rail renders in a separate bounded view so native glass stays visible', () => {
  const html = read('src', 'renderer', 'sidebar.html')
  const css = read('src', 'renderer', 'sidebar.css')
  const js = read('src', 'renderer', 'sidebar.js')
  const main = read('src', 'main', 'index.js')
  const frameCss = read('src', 'renderer', 'frame.css')
  const cornerCss = read('src', 'renderer', 'corner-mask.css')
  assert.match(html, /id="favorites"/)
  assert.match(css, /\.sidebar-surface/)
  assert.match(css, /border-radius:\s*var\(--outer-radius\)\s+0\s+0\s+var\(--outer-radius\)/)
  assert.doesNotMatch(css, /radial-gradient[\s\S]+linear-gradient/, 'sidebar does not paint an independent shell material')
  assert.match(js, /openFavorite/)
  assert.match(js, /sameFavoriteSite/)
  assert.match(js, /onWindowState/)
  assert.match(js, /classList\.toggle\('sidebar-closed'/)
  assert.match(css, /body\.sidebar-closed\s+\.favorites\s*\{[^}]*opacity:\s*0/s)
  assert.match(main, /sidebarView/)
  assert.match(main, /contentView\.setBorderRadius/)
  assert.match(main, /frame\.html/)
  assert.doesNotMatch(frameCss, /#a43c03|#542006/i, 'frame does not own a competing lower-right gradient')
  assert.match(frameCss, /border-radius:\s*0\s+0\s+var\(--outer-radius\)\s+0/)
  assert.match(frameCss, /\.maximized\s+\.frame-surface/)
  assert.match(main, /pageCornerMasks/)
  assert.match(main, /CORNER_MASK_INPUT/)
  assert.match(main, /sendInputEvent/, 'visible page pixels beneath a mask remain interactive')
  assert.match(cornerCss, /radial-gradient/)
  assert.match(cornerCss, /transparent/)
  assert.doesNotMatch(css, /\.sidebar-surface\s*\{[^}]*border-(?:left|bottom)/s)
})

test('sidebar keeps a native address field above its unchanged Favorite grid', () => {
  const sidebarHtml = read('src', 'renderer', 'sidebar.html')
  const sidebarCss = read('src', 'renderer', 'sidebar.css')
  const sidebarJs = read('src', 'renderer', 'sidebar.js')
  const main = read('src', 'main', 'index.js')

  assert.match(sidebarHtml, /<form class="sidebar-address" id="sidebar-address">/)
  assert.match(sidebarHtml, /<input[^>]+id="sidebar-address-input"/)
  assert.match(sidebarHtml, /assets\/copy-link\.svg/)
  assert.match(sidebarCss, /\.sidebar-content\s*\{[\s\S]*display:\s*grid/)
  assert.match(sidebarCss, /\.sidebar-address\s*\{[\s\S]*background:\s*rgba\(255, 255, 255, \.075\)/)
  assert.match(sidebarCss, /\.sidebar-address-copy img\s*\{[\s\S]*filter:\s*brightness\(0\) invert\(1\)/)
  assert.match(sidebarJs, /window\.ember\.go\(addressInput\.value\)/)
  assert.match(sidebarJs, /window\.ember\.copyActiveUrl\(\)/)
  assert.match(sidebarJs, /if \(addressEditing\) return/)
  const copyLinkIcon = path.join(__dirname, '..', 'src', 'renderer', 'assets', 'copy-link.svg')
  assert.ok(fs.existsSync(copyLinkIcon))
  assert.match(fs.readFileSync(copyLinkIcon, 'utf8'), /<path[^>]+stroke-linecap="round"/)
  assert.match(main, /ipcMain\.handle\(IPC\.SIDEBAR_COPY_ACTIVE_URL/)
  assert.match(main, /active\?\.webContents\?\.getURL\?\.\(\) \|\| active\?\.url \|\| ''/)
  assert.match(main, /clipboard\.writeText\(url\)/)
  assert.match(main, /inputOwner\?\.sidebarView\?\.webContents === wc && inputOwner\.sidebarEditing/)
})

test('sidebar address display and copy feedback stay polished without moving Favorites', () => {
  const sidebarCss = read('src', 'renderer', 'sidebar.css')
  const sidebarJs = read('src', 'renderer', 'sidebar.js')
  const main = read('src', 'main', 'index.js')
  const toastHtml = read('src', 'renderer', 'pages', 'copy-toast.html')
  const toastCss = read('src', 'renderer', 'pages', 'copy-toast.css')
  const toastJs = read('src', 'renderer', 'pages', 'copy-toast.js')

  assert.match(sidebarJs, /function displayAddress\(url\)/)
  assert.ok(sidebarJs.includes("replace(/^https?:\\/\\//i, '')"))
  assert.ok(sidebarJs.includes("replace(/^www\\./i, '')"))
  assert.match(sidebarJs, /addressInput\.select\(\)/)
  assert.match(sidebarCss, /\.sidebar-address:focus-within[^}]*background:\s*rgba\(255, 255, 255, \.18\)/)
  assert.match(sidebarCss, /\.sidebar-address input\s*\{[\s\S]*background:\s*transparent[\s\S]*box-shadow:\s*none[\s\S]*border-radius:\s*0/)
  assert.match(sidebarCss, /\.sidebar-address-copy:hover img[^}]*transform:/)
  assert.match(sidebarCss, /\.sidebar-address-copy:active img[^}]*transform:/)
  assert.match(main, /copyToast\.show\(\)/)
  assert.match(toastHtml, /copy-toast-progress/)
  assert.match(toastCss, /copy-toast-enter/)
  assert.match(toastCss, /copy-toast-exit/)
  assert.match(toastCss, /border-radius:\s*999px/)
  assert.match(toastCss, /copy-toast-life/)
  assert.match(toastJs, /openSequence/)
})

test('bounded native surfaces sample one synchronized shell material', () => {
  const material = read('src', 'renderer', 'shell-material.css')
  const metrics = read('src', 'renderer', 'shell-metrics.js')
  const chromeHtml = read('src', 'renderer', 'chrome.html')
  const sidebarHtml = read('src', 'renderer', 'sidebar.html')
  const frameHtml = read('src', 'renderer', 'frame.html')
  const cornerHtml = read('src', 'renderer', 'corner-mask.html')
  const cornerCss = read('src', 'renderer', 'corner-mask.css')

  assert.match(material, /--shell-material:/)
  assert.match(material, /radial-gradient[\s\S]+radial-gradient[\s\S]+linear-gradient/)
  assert.match(material, /background-size:\s*var\(--shell-width\) var\(--shell-height\)/)
  assert.match(material, /calc\(0px - var\(--shell-x\)\)/)
  for (const html of [chromeHtml, sidebarHtml, frameHtml, cornerHtml]) {
    assert.match(html, /shell-material\.css/)
    assert.match(html, /shell-metrics\.js/)
  }
  assert.match(metrics, /--shell-width/)
  assert.match(metrics, /--shell-x/)
  assert.match(cornerCss, /mask-image/)
  assert.match(cornerCss, /var\(--shell-material\)/)
  assert.doesNotMatch(cornerCss, /#a43c03|#5c2205/i)
})

test('tab lifecycle states use natural widths, measured fades, and hover-only close controls', () => {
  const css = read('src', 'renderer', 'chrome.css')
  const js = read('src', 'renderer', 'chrome.js')

  assert.match(css, /\.tab\s*\{[^}]*width:\s*max-content/)
  assert.match(css, /\.tab-title\.overflowing[\s\S]+mask-image:/)
  assert.doesNotMatch(css, /\.tab-title\s*\{[^}]*text-overflow:\s*ellipsis/)
  assert.match(css, /\.tab-close\s*\{[^}]*opacity:\s*0/)
  assert.match(css, /\.tab:hover\s+\.tab-close\s*\{[^}]*opacity:\s*1/)
  assert.match(css, /\.tab\.asleep\s+\.tab-favicon\s*\{[^}]*grayscale\(1\)/)
  assert.match(css, /\.tab\.active[\s\S]+rgba\(255,\s*91,\s*0/)
  assert.match(js, /className = 'tab-sleep'/)
  assert.match(js, /ResizeObserver/)
  assert.match(js, /scrollWidth > title\.clientWidth/)
})

test('tabs reorder with a custom drag image and can pin into the full Favorite grid', () => {
  const chromeJs = read('src', 'renderer', 'chrome.js')
  const chromeCss = read('src', 'renderer', 'chrome.css')
  const sidebarJs = read('src', 'renderer', 'sidebar.js')
  const sidebarCss = read('src', 'renderer', 'sidebar.css')

  assert.match(chromeJs, /el\.draggable = true/)
  assert.match(chromeJs, /application\/x-ember-tab/)
  assert.match(chromeJs, /setDragImage/)
  assert.match(chromeJs, /window\.ember\.reorderTab/)
  assert.match(chromeJs, /getBoundingClientRect\(\)/)
  assert.match(chromeCss, /\.tab\.dragging/)
  assert.match(chromeCss, /transition:[^}]*transform[^}]*150ms/s)
  assert.match(chromeCss, /-webkit-app-region:\s*no-drag/)

  assert.match(sidebarJs, /browserState\.tabs\.some/)
  assert.match(sidebarJs, /pinFavoriteFromTab/)
  assert.match(sidebarJs, /favoriteContextMenu/)
  assert.match(sidebarJs, /application\/x-ember-tab/)
  assert.match(sidebarCss, /\.favorites\.drop-ready/)
  assert.match(sidebarCss, /\.favorites\s*\{[^}]*height:\s*var\(--favorite-grid-height\)/s)
  assert.match(sidebarCss, /\.favorite\.is-open/)
  for (const token of ['--favorite-columns', '--favorite-rows', '--favorite-tile-height', '--favorite-gap', '--favorite-grid-height']) {
    assert.match(sidebarCss, new RegExp(token))
  }
  assert.match(sidebarCss, /repeat\(var\(--favorite-columns\)/)
  assert.match(sidebarCss, /\.favorite img\s*\{[^}]*width:\s*19px[^}]*height:\s*19px/s)
  assert.match(sidebarJs, /favorite-slot/)
  assert.match(sidebarJs, /previewFavoritePlacement/)
  assert.match(sidebarJs, /node\.animate/)
  assert.match(sidebarJs, /moveFavorite/)
  assert.match(sidebarJs, /pinFavoriteFromTab\(id, index\)/)
  assert.match(sidebarJs, /finally\s*\{[^}]*dropPending = false[^}]*resetPreview\(\)/s)
})

test('extension icon and metadata share one keyboard-accessible launcher', () => {
  const js = read('src', 'renderer', 'pages', 'extensions.js')
  assert.match(js, /launch\.append\(icon, meta\)/)
  assert.match(js, /launch\.dataset\.extensionId = ext\.id/)
  assert.match(js, /img\.alt = ''/)
  assert.match(js, /remove\.setAttribute\('aria-label', `Remove \$\{ext\.name\}`\)/)
  assert.doesNotMatch(js, /meta\.onclick/)
})

test('browser chrome mirrors authoritative extension-panel visibility', () => {
  const js = read('src', 'renderer', 'chrome.js')
  assert.match(js, /window\.ember\.onPanelChanged/)
  assert.match(js, /setAttribute\('aria-expanded', String\(open\)\)/)
})

test('New Tab uses the square meteor crop while pages retain their favicon', () => {
  const js = read('src', 'renderer', 'chrome.js')
  const css = read('src', 'renderer', 'chrome.css')
  const brandCss = read('src', 'renderer', 'brand.css')
  assert.match(js, /window\.EmberBrand\.APP_ICON_ASSET/)
  assert.match(js, /tab\.favicon/)
  assert.match(js, /function assetUrl/)
  assert.match(js, /img\.src = tab\.favicon \|\| assetUrl\(fallback\)/)
  assert.match(brandCss, /\.ember-chrome-icon[^}]*object-fit:\s*contain/s)
  // A favicon box is square, so the long chrome mark must not be used here.
  assert.match(css, /\.tab-favicon\.newtab-favicon\s*\{[^}]*width:\s*16px[^}]*height:\s*16px/s)
})

test('upload picker is a real glass overlay with browse, clipboard, and recent actions', () => {
  const html = read('src', 'renderer', 'pages', 'upload.html')
  const css = read('src', 'renderer', 'pages', 'upload.css')
  const js = read('src', 'renderer', 'pages', 'upload.js')
  assert.match(html, /href="\/glass\.css"/)
  assert.match(html, /id="show-all-files"/)
  assert.match(html, /id="clipboard-slot"/)
  assert.match(html, /id="recent-files"/)
  assert.match(js, /window\.emberOverlay\.action\('browse'/)
  assert.match(js, /window\.emberOverlay\.action\('clipboard'/)
  assert.match(js, /window\.emberOverlay\.action\('recent'/)
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /id="upload-switcher-map"/)
  assert.match(html, /upload-optics\.js/)
  assert.match(html, /id="upload-shell"/)
  assert.match(css, /\.upload-shell\[data-opening="true"\]/)
  assert.match(css, /backdrop-filter:\s*url\(#switcher\) blur\(\.65px\)/)
  assert.match(css, /backdrop-filter:\s*url\(#toggler\)/)
  assert.match(html, /id="upload-hover-source"/)
  assert.match(css, /#upload-hover-source[\s\S]+background-position:\s*var\(--sample-x\) var\(--sample-y\)/)
  assert.doesNotMatch(css, /blur\(8px\)/)
  assert.doesNotMatch(css, /rgba\(12,\s*12,\s*14,\s*\.26\)/)
  assert.match(js, /shell\.animate\(/)
  assert.match(js, /pointerenter/)
})

test('shared glass surface includes refractive edges, backdrop sampling, and specular light', () => {
  const css = read('src', 'renderer', 'glass.css')
  assert.match(css, /glass-backdrop/)
  assert.match(css, /filter: blur/)
  assert.match(css, /inset 0 1px/)
  assert.match(css, /radial-gradient/)
})

test('context menu adapts one canonical map to outer geometry and raw selector sampling', () => {
  const html = read('src', 'renderer', 'pages', 'context-menu.html')
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  const js = read('src', 'renderer', 'pages', 'context-menu.js')
  const protocol = read('src', 'main', 'protocol.js')
  const crypto = require('node:crypto')
  const expectedMapHash = '6475a2bf80d1dad57b98ffe7bb38acd62eac3386abdca245e73dd9f36287813d'
  const hash = (value) => crypto.createHash('sha256').update(value).digest('hex')
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /glass-switcher-map\.webp/)
  assert.doesNotMatch(html, /glass-toggler-map\.webp/)
  assert.doesNotMatch(protocol, /glass-toggler-map\.webp/)
  assert.match(html, /id="switcher-map"/)
  assert.match(html, /context-menu-optics\.js/)
  assert.match(html, /stdDeviation="0\.004"/)
  assert.match(html, /stdDeviation="0\.01"/)
  assert.match(html, /<feDisplacementMap[^>]+scale="0\.08"/)
  assert.match(html, /<feDisplacementMap[^>]+scale="0\.05"/)
  assert.doesNotMatch(html, /feTurbulence/)
  assert.equal(hash(bytes('src', 'renderer', 'assets', 'glass-switcher-map.webp')), expectedMapHash)
  assert.doesNotMatch(css, /object-fit:\s*cover/)
  assert.doesNotMatch(css, /blur\(22px\)/)
  assert.doesNotMatch(css, /scale\(1\.04\)/)
  assert.doesNotMatch(css, /blur\(8px\)/)
  assert.match(css, /backdrop-filter:\s*url\(#switcher\) blur\(\.65px\)/)
  assert.match(html, /id="selector-source"/)
  assert.match(css, /#selector-source[\s\S]+background-position:\s*var\(--sample-x\) var\(--sample-y\)/)
  assert.match(css, /#selector-sample[\s\S]+backdrop-filter:\s*url\(#toggler\)/)
  assert.match(css, /#selector-lens/)
  assert.match(css, /transition:\s*--lens-x/)
  assert.match(html, /id="context-menu"/)
  assert.match(css, /\.menu-item:focus-visible/)
  assert.match(js, /window\.emberOverlay\.action\(item\.id\)/)
  assert.match(js, /pointerenter/)
  assert.match(js, /source\.style\.backgroundImage/)
  assert.match(js, /setBackdropRect/)
  assert.match(js, /backdrop\.removeAttribute\('src'\)/)
  assert.match(js, /menu\.addEventListener\('scroll'/)
  assert.match(css, /overflow-y:\s*auto/)
  assert.match(js, /ArrowDown/)
  assert.match(js, /ArrowUp/)
  assert.match(js, /Home/)
  assert.match(js, /End/)
  assert.match(js, /Escape/)
})

test('visual QA captures selector travel over dark and light contrast backdrops', () => {
  const capture = read('scripts', 'capture-ui.js')
  assert.match(capture, /copy-toast/)
  assert.match(capture, /context-grid/)
  assert.match(capture, /context-saturated/)
  assert.match(capture, /context-type-contrast/)
  assert.match(capture, /context-photo/)
  assert.match(capture, /activePosition/)
})

test('visual QA exercises upload optics on high-contrast and colourful page captures', () => {
  const capture = read('scripts', 'capture-ui.js')
  assert.match(capture, /upload-contrast/)
  assert.match(capture, /upload-colour/)
  assert.match(capture, /upload-hover/)
  assert.match(capture, /uploadBackdropRect/)
})

test('context glass stays neutral and frosts enough to read its own labels', () => {
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  assert.match(css, /\.menu-shell[\s\S]+background:\s*transparent/)
  // Achromatic, so the captured page still drives the hue — but opaque and
  // blurred enough that a menu label is not competing with the page's own
  // text showing through it.
  assert.match(css, /background-color:\s*var\(--frost-fill/)
  // Both the surface and the hover lens sample the capture, so both wear the
  // one shared frost filter rather than each inventing a blur radius.
  assert.match(css, /\.outer-texture[\s\S]+?filter:\s*var\(--frost-capture\)/)
  assert.match(css, /#selector-source[\s\S]+?filter:\s*var\(--frost-capture\)/)
  const theme = read('src', 'renderer', 'theme.css')
  const blur = Number(theme.match(/--frost-capture:\s*blur\((\d+)px\)/)[1])
  assert.ok(blur >= 16, `capture must be blurred past legibility, got ${blur}px`)
  assert.doesNotMatch(css, /rgba\(25,\s*18,\s*26,\s*\.52\)/, 'no violet tint')
  assert.doesNotMatch(css, /rgba\(15,\s*10,\s*17,\s*\.72\)/, 'no violet tint')
})

test('context menu opens as a reduced-motion-safe popover and does not replay on relayout', () => {
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  const js = read('src', 'renderer', 'pages', 'context-menu.js')
  assert.match(css, /\.menu-shell\[data-opening="true"\]/)
  assert.match(css, /scale\(\.96\)/)
  assert.match(css, /--open-motion:\s*220ms/)
  assert.match(css, /cubic-bezier\(\.16,\s*1,\s*\.3,\s*1\)/)
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]+--open-motion:\s*1ms linear/)
  assert.match(js, /state\.openSequence !== openSequence/)
  assert.match(js, /requestAnimationFrame/)
  assert.match(js, /shell\.animate\(/)
})

test('the conversion popup is frosted and replays its entrance on every open', () => {
  const html = read('src', 'renderer', 'pages', 'conversion.html')
  const css = read('src', 'renderer', 'pages', 'conversion.css')
  const js = read('src', 'renderer', 'pages', 'conversion.js')
  assert.match(html, /class="shell glass-frosted"/)
  assert.doesNotMatch(css, /\.shell\s*\{[^}]*background:\s*var\(--glass-bg\)/s, 'no violet tint')
  // The overlay view is reused, so the entrance has to be a class the page
  // re-adds. A finished CSS animation is no longer in getAnimations(), which
  // is why rewinding what it returned did nothing after the first open.
  assert.match(css, /\.shell\.opening\s*\{[^}]*animation:/s)
  assert.match(js, /classList\.remove\('opening'\)/)
  assert.match(js, /classList\.add\('opening'\)/)
  assert.match(js, /els\.shell\.offsetWidth/, 'a reflow between, or the class swap is coalesced away')
})

test('every frosted surface takes its blur from one shared filter', () => {
  const theme = read('src', 'renderer', 'theme.css')
  assert.match(theme, /--frost-capture:\s*blur\(\d+px\)/)
  assert.match(theme, /--frost-fill:/)
  const glass = read('src', 'renderer', 'glass.css')
  // The light palette lifts the capture rather than dimming it, or a frosted
  // panel over a bright page reads as a dark smear.
  assert.match(glass, /\[data-backdrop="light"\][\s\S]*?--frost-capture:[^;]*brightness\(1\./)
  for (const file of [['upload'], ['context-menu']]) {
    const css = read('src', 'renderer', 'pages', `${file[0]}.css`)
    assert.match(css, /filter:\s*var\(--frost-capture\)/, `${file[0]} uses the shared frost`)
  }
})

test('the omnibox names the quick search before you commit to it', () => {
  const html = read('src', 'renderer', 'chrome.html')
  const css = read('src', 'renderer', 'chrome.css')
  const js = read('src', 'renderer', 'chrome.js')

  assert.match(html, /id="bang-chip"/)
  assert.match(html, /id="bang-tip"/)
  assert.match(css, /\.bang-chip\.engaged/, 'a committed engine looks different from a guess')
  // Matching happens in the renderer, not over IPC, so it lands on the keystroke.
  assert.match(js, /window\.ember\.resolveInput/)
  assert.match(js, /addEventListener\('input', \(\) => \{ omniboxDirty = true; renderBang\(\) \}\)/)
  // Tab commits, Backspace steps back out, and submit puts the keyword back.
  assert.match(js, /e\.key === 'Tab'/)
  assert.match(js, /e\.key === 'Backspace' && engaged/)
  assert.match(js, /engaged \? `\$\{engaged\.alias\} \$\{typed\}`\.trim\(\) : typed/)
})

test('the new tab search names the quick search too', () => {
  const js = read('src', 'renderer', 'pages', 'newtab.js')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  const search = read('src', 'renderer', 'pages', 'liquid-glass-search.js')

  assert.match(search, /id="q-chip"/)
  assert.match(css, /\.liquid-glass-search-chip/)
  // A sandboxed page cannot load the resolver, so it asks the one main uses.
  assert.match(js, /window\.ember\.omnibox\.resolve/)
  assert.match(js, /if \(asked !== latest\) return/, 'a stale answer must not win')
})

test('settings can add, edit, remove, and reset the ordered Favorite rail', () => {
  const html = read('src', 'renderer', 'pages', 'settings.html')
  const css = read('src', 'renderer', 'pages', 'settings.css')
  const js = read('src', 'renderer', 'pages', 'settings.js')
  const main = read('src', 'main', 'index.js')

  for (const id of ['favorite-list', 'favorite-new', 'favorite-name', 'favorite-url', 'favorite-reset', 'favorite-columns', 'favorite-rows', 'favorite-grid-apply']) {
    assert.match(html, new RegExp(`id="${id}"`), id)
  }
  assert.match(css, /\.favorite-row/)
  assert.match(js, /function renderFavorites/)
  assert.match(js, /api\?\.set\('favorites'/)
  assert.match(js, /api\?\.set\('favoriteGrid'/)
  assert.match(js, /FAVORITE_COLUMN_OPTIONS = \[1, 2, 3, 4\]/)
  assert.match(js, /FAVORITE_ROW_OPTIONS = \[1, 2, 3, 4, 5, 6, 7\]/)
  assert.match(main, /preference === 'favoriteGrid'[^\n]+sync\('favorites', snapshot\.favorites\)/)
  assert.match(js, /favorite-reset/)
  assert.match(js, /row\.contains\(event\.relatedTarget\)/, 'moving between row inputs does not rebuild the editor')
  assert.match(js, /const edited = currentFavorite\(\)/, 'reordering preserves live input values')
  assert.match(js, /favorite-remove/)
})
