const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts), 'utf8')
const bytes = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts))

test('new tab composes its masthead from the meteor and a Necosmic wordmark', () => {
  const html = read('src', 'renderer', 'pages', 'newtab.html')
  const protocol = read('src', 'main', 'protocol.js')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  assert.match(html, /id="ember-brand"/)
  assert.match(html, /href="\/theme\.css"/)
  assert.match(protocol, /\['\/theme\.css', path\.join\(RENDERER, 'theme\.css'\)\]/)
  assert.match(html, /\/brand\.js/)
  assert.match(html, /\/brand\.css/)
  assert.match(protocol, /Necosmic-PersonalUse\.otf/)
  assert.match(css, /@font-face/)
  assert.match(css, /font-family:\s*'Necosmic'/)
  assert.match(css, /\.ember-wordmark[\s\S]+color:\s*#fff/)
  assert.match(css, /\.ember-meteor[\s\S]+filter:\s*drop-shadow/)
  const wordmarkRule = css.match(/\.ember-wordmark\s*\{([^}]*)\}/)?.[1] || ''
  assert.doesNotMatch(wordmarkRule, /filter\s*:/)
})

test('browser chrome provides a compact live bookmarks bar', () => {
  const html = read('src', 'renderer', 'chrome.html')
  assert.match(html, /id="bookmarks-bar"/)
  assert.match(html, /id="bookmarks-items"/)
  assert.match(html, /id="import-bookmarks"/)
})

test('extension icon and metadata share one keyboard-accessible launcher', () => {
  const js = read('src', 'renderer', 'pages', 'extensions.js')
  assert.match(js, /launch\.append\(icon, meta\)/)
  assert.match(js, /launch\.dataset\.extensionId = ext\.id/)
  assert.match(js, /img\.alt = ''/)
  assert.match(js, /remove\.setAttribute\('aria-label', `Remove \$\{ext\.name\}`\)/)
  assert.doesNotMatch(js, /meta\.onclick/)
})

test('browser chrome mirrors authoritative extension-panel visibility', () => {
  const js = read('src', 'renderer', 'chrome.js')
  assert.match(js, /window\.ember\.onPanelChanged/)
  assert.match(js, /setAttribute\('aria-expanded', String\(open\)\)/)
})

test('tabs fall back to the Ember meteor when a page has no favicon', () => {
  const js = read('src', 'renderer', 'chrome.js')
  assert.match(js, /img\.src = tab\.favicon \|\| window\.EmberBrand\.ICON_ASSET/)
})

test('upload picker is a real glass overlay with browse, clipboard, and recent actions', () => {
  const html = read('src', 'renderer', 'pages', 'upload.html')
  const css = read('src', 'renderer', 'pages', 'upload.css')
  const js = read('src', 'renderer', 'pages', 'upload.js')
  assert.match(html, /href="\/glass\.css"/)
  assert.match(html, /id="show-all-files"/)
  assert.match(html, /id="clipboard-slot"/)
  assert.match(html, /id="recent-files"/)
  assert.match(js, /window\.emberOverlay\.action\('browse'/)
  assert.match(js, /window\.emberOverlay\.action\('clipboard'/)
  assert.match(js, /window\.emberOverlay\.action\('recent'/)
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /id="upload-shell"/)
  assert.match(css, /\.upload-shell\[data-opening="true"\]/)
  assert.match(css, /backdrop-filter:\s*url\(#switcher\)/)
  assert.match(css, /backdrop-filter:\s*url\(#toggler\)/)
  assert.match(js, /shell\.animate\(/)
  assert.match(js, /pointerenter/)
})

test('shared glass surface includes refractive edges, backdrop sampling, and specular light', () => {
  const css = read('src', 'renderer', 'glass.css')
  assert.match(css, /glass-backdrop/)
  assert.match(css, /filter: blur/)
  assert.match(css, /inset 0 1px/)
  assert.match(css, /radial-gradient/)
})

test('context menu uses the canonical fixed-map switcher and toggler filters', () => {
  const html = read('src', 'renderer', 'pages', 'context-menu.html')
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  const js = read('src', 'renderer', 'pages', 'context-menu.js')
  const crypto = require('node:crypto')
  const expectedMapHash = '6475a2bf80d1dad57b98ffe7bb38acd62eac3386abdca245e73dd9f36287813d'
  const hash = (value) => crypto.createHash('sha256').update(value).digest('hex')
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /glass-switcher-map\.webp/)
  assert.match(html, /glass-toggler-map\.webp/)
  assert.match(html, /stdDeviation="0\.04"/)
  assert.match(html, /stdDeviation="0\.01"/)
  assert.match(html, /<feDisplacementMap[^>]+scale="0\.5"/)
  assert.doesNotMatch(html, /feTurbulence/)
  assert.equal(hash(bytes('src', 'renderer', 'assets', 'glass-switcher-map.webp')), expectedMapHash)
  assert.equal(hash(bytes('src', 'renderer', 'assets', 'glass-toggler-map.webp')), expectedMapHash)
  assert.doesNotMatch(css, /object-fit:\s*cover/)
  assert.doesNotMatch(css, /blur\(22px\)/)
  assert.doesNotMatch(css, /scale\(1\.04\)/)
  assert.match(css, /backdrop-filter:\s*blur\(8px\) url\(#switcher\)/)
  assert.match(css, /backdrop-filter:\s*url\(#toggler\)/)
  assert.match(css, /#selector-lens/)
  assert.match(css, /transition:\s*--lens-x/)
  assert.match(html, /id="context-menu"/)
  assert.match(css, /\.menu-item:focus-visible/)
  assert.match(js, /window\.emberOverlay\.action\(item\.id\)/)
  assert.match(js, /pointerenter/)
  assert.match(js, /backdrop\.removeAttribute\('src'\)/)
  assert.match(js, /menu\.addEventListener\('scroll'/)
  assert.match(css, /overflow-y:\s*auto/)
  assert.match(js, /ArrowDown/)
  assert.match(js, /ArrowUp/)
  assert.match(js, /Home/)
  assert.match(js, /End/)
  assert.match(js, /Escape/)
})

test('visual QA captures selector travel over dark and light contrast backdrops', () => {
  const capture = read('scripts', 'capture-ui.js')
  assert.match(capture, /context-dark-first/)
  assert.match(capture, /context-dark-middle/)
  assert.match(capture, /context-dark-bottom/)
  assert.match(capture, /context-light-middle/)
  assert.match(capture, /activePosition/)
})

test('context glass stays neutral so captured page color drives the surface', () => {
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  assert.match(css, /\.menu-shell[\s\S]+background:\s*transparent/)
  assert.match(css, /background-color:\s*rgba\(12,\s*12,\s*14,\s*\.26\)/)
  assert.doesNotMatch(css, /rgba\(25,\s*18,\s*26,\s*\.52\)/)
  assert.doesNotMatch(css, /rgba\(15,\s*10,\s*17,\s*\.72\)/)
})
