const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts), 'utf8')
const bytes = (...parts) => fs.readFileSync(path.join(__dirname, '..', ...parts))

test('new tab composes its masthead from the meteor and a Necosmic wordmark', () => {
  const html = read('src', 'renderer', 'pages', 'newtab.html')
  const protocol = read('src', 'main', 'protocol.js')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  assert.match(html, /id="ember-brand"/)
  assert.match(html, /href="\/theme\.css"/)
  assert.match(protocol, /\['\/theme\.css', path\.join\(RENDERER, 'theme\.css'\)\]/)
  assert.match(html, /\/brand\.js/)
  assert.match(html, /\/brand\.css/)
  assert.match(protocol, /Necosmic-PersonalUse\.otf/)
  assert.match(css, /@font-face/)
  assert.match(css, /font-family:\s*'Necosmic'/)
  assert.match(css, /\.ember-wordmark[\s\S]+color:\s*#fff/)
  assert.match(css, /\.ember-meteor[\s\S]+filter:\s*drop-shadow/)
  const wordmarkRule = css.match(/\.ember-wordmark\s*\{([^}]*)\}/)?.[1] || ''
  assert.doesNotMatch(wordmarkRule, /filter\s*:/)
})

test('new tab keeps Ember content above configurable native double-blur layers', () => {
  const html = read('src', 'renderer', 'pages', 'newtab.html')
  const css = read('src', 'renderer', 'pages', 'newtab.css')
  const js = read('src', 'renderer', 'pages', 'native-glass.js')
  const main = read('src', 'main', 'index.js')
  assert.match(html, /class="native-glass-page"/)
  assert.match(html, /native-glass\.js/)
  assert.match(html, /data-native-glass-search/)
  assert.match(js, /nativeGlass\?\.getSettings/)
  assert.match(js, /nativeGlass\?\.layoutSearch/)
  assert.match(css, /html,\s*body\s*\{[^}]*background:\s*transparent/)
  assert.match(css, /\.search[\s\S]+background:\s*transparent/)
  assert.doesNotMatch(css, /\.search\s*\{[^}]*backdrop-filter/)
  assert.match(css, /\.go[\s\S]+background:\s*linear-gradient/)
  assert.match(main, /function broadcastBookmarks[\s\S]+layoutNativeBackdrop\(\)/)
  assert.match(main, /transparent:\s*true/)
  assert.match(main, /backgroundColor:\s*'#00000000'/)
})

test('browser chrome provides a compact live bookmarks bar', () => {
  const html = read('src', 'renderer', 'chrome.html')
  assert.match(html, /id="bookmarks-bar"/)
  assert.match(html, /id="bookmarks-items"/)
  assert.match(html, /id="import-bookmarks"/)
})

test('extension icon and metadata share one keyboard-accessible launcher', () => {
  const js = read('src', 'renderer', 'pages', 'extensions.js')
  assert.match(js, /launch\.append\(icon, meta\)/)
  assert.match(js, /launch\.dataset\.extensionId = ext\.id/)
  assert.match(js, /img\.alt = ''/)
  assert.match(js, /remove\.setAttribute\('aria-label', `Remove \$\{ext\.name\}`\)/)
  assert.doesNotMatch(js, /meta\.onclick/)
})

test('browser chrome mirrors authoritative extension-panel visibility', () => {
  const js = read('src', 'renderer', 'chrome.js')
  assert.match(js, /window\.ember\.onPanelChanged/)
  assert.match(js, /setAttribute\('aria-expanded', String\(open\)\)/)
})

test('tabs fall back to the Ember meteor when a page has no favicon', () => {
  const js = read('src', 'renderer', 'chrome.js')
  assert.match(js, /img\.src = tab\.favicon \|\| window\.EmberBrand\.ICON_ASSET/)
})

test('upload picker is a real glass overlay with browse, clipboard, and recent actions', () => {
  const html = read('src', 'renderer', 'pages', 'upload.html')
  const css = read('src', 'renderer', 'pages', 'upload.css')
  const js = read('src', 'renderer', 'pages', 'upload.js')
  assert.match(html, /href="\/glass\.css"/)
  assert.match(html, /id="show-all-files"/)
  assert.match(html, /id="clipboard-slot"/)
  assert.match(html, /id="recent-files"/)
  assert.match(js, /window\.emberOverlay\.action\('browse'/)
  assert.match(js, /window\.emberOverlay\.action\('clipboard'/)
  assert.match(js, /window\.emberOverlay\.action\('recent'/)
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /id="upload-switcher-map"/)
  assert.match(html, /upload-optics\.js/)
  assert.match(html, /id="upload-shell"/)
  assert.match(css, /\.upload-shell\[data-opening="true"\]/)
  assert.match(css, /backdrop-filter:\s*url\(#switcher\) blur\(\.65px\)/)
  assert.match(css, /backdrop-filter:\s*url\(#toggler\)/)
  assert.match(html, /id="upload-hover-source"/)
  assert.match(css, /#upload-hover-source[\s\S]+background-position:\s*var\(--sample-x\) var\(--sample-y\)/)
  assert.doesNotMatch(css, /blur\(8px\)/)
  assert.doesNotMatch(css, /rgba\(12,\s*12,\s*14,\s*\.26\)/)
  assert.match(js, /shell\.animate\(/)
  assert.match(js, /pointerenter/)
})

test('shared glass surface includes refractive edges, backdrop sampling, and specular light', () => {
  const css = read('src', 'renderer', 'glass.css')
  assert.match(css, /glass-backdrop/)
  assert.match(css, /filter: blur/)
  assert.match(css, /inset 0 1px/)
  assert.match(css, /radial-gradient/)
})

test('context menu adapts one canonical map to outer geometry and raw selector sampling', () => {
  const html = read('src', 'renderer', 'pages', 'context-menu.html')
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  const js = read('src', 'renderer', 'pages', 'context-menu.js')
  const protocol = read('src', 'main', 'protocol.js')
  const crypto = require('node:crypto')
  const expectedMapHash = '6475a2bf80d1dad57b98ffe7bb38acd62eac3386abdca245e73dd9f36287813d'
  const hash = (value) => crypto.createHash('sha256').update(value).digest('hex')
  assert.match(html, /id="switcher"/)
  assert.match(html, /id="toggler"/)
  assert.match(html, /glass-switcher-map\.webp/)
  assert.doesNotMatch(html, /glass-toggler-map\.webp/)
  assert.doesNotMatch(protocol, /glass-toggler-map\.webp/)
  assert.match(html, /id="switcher-map"/)
  assert.match(html, /context-menu-optics\.js/)
  assert.match(html, /stdDeviation="0\.004"/)
  assert.match(html, /stdDeviation="0\.01"/)
  assert.match(html, /<feDisplacementMap[^>]+scale="0\.08"/)
  assert.match(html, /<feDisplacementMap[^>]+scale="0\.05"/)
  assert.doesNotMatch(html, /feTurbulence/)
  assert.equal(hash(bytes('src', 'renderer', 'assets', 'glass-switcher-map.webp')), expectedMapHash)
  assert.doesNotMatch(css, /object-fit:\s*cover/)
  assert.doesNotMatch(css, /blur\(22px\)/)
  assert.doesNotMatch(css, /scale\(1\.04\)/)
  assert.doesNotMatch(css, /blur\(8px\)/)
  assert.match(css, /backdrop-filter:\s*url\(#switcher\) blur\(\.65px\)/)
  assert.match(html, /id="selector-source"/)
  assert.match(css, /#selector-source[\s\S]+background-position:\s*var\(--sample-x\) var\(--sample-y\)/)
  assert.match(css, /#selector-sample[\s\S]+backdrop-filter:\s*url\(#toggler\)/)
  assert.match(css, /#selector-lens/)
  assert.match(css, /transition:\s*--lens-x/)
  assert.match(html, /id="context-menu"/)
  assert.match(css, /\.menu-item:focus-visible/)
  assert.match(js, /window\.emberOverlay\.action\(item\.id\)/)
  assert.match(js, /pointerenter/)
  assert.match(js, /source\.style\.backgroundImage/)
  assert.match(js, /setBackdropRect/)
  assert.match(js, /backdrop\.removeAttribute\('src'\)/)
  assert.match(js, /menu\.addEventListener\('scroll'/)
  assert.match(css, /overflow-y:\s*auto/)
  assert.match(js, /ArrowDown/)
  assert.match(js, /ArrowUp/)
  assert.match(js, /Home/)
  assert.match(js, /End/)
  assert.match(js, /Escape/)
})

test('visual QA captures selector travel over dark and light contrast backdrops', () => {
  const capture = read('scripts', 'capture-ui.js')
  assert.match(capture, /context-grid/)
  assert.match(capture, /context-saturated/)
  assert.match(capture, /context-type-contrast/)
  assert.match(capture, /context-photo/)
  assert.match(capture, /activePosition/)
})

test('visual QA exercises upload optics on high-contrast and colourful page captures', () => {
  const capture = read('scripts', 'capture-ui.js')
  assert.match(capture, /upload-contrast/)
  assert.match(capture, /upload-colour/)
  assert.match(capture, /upload-hover/)
  assert.match(capture, /uploadBackdropRect/)
})

test('context glass stays neutral so captured page color drives the surface', () => {
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  assert.match(css, /\.menu-shell[\s\S]+background:\s*transparent/)
  assert.match(css, /background-color:\s*rgba\(255,\s*255,\s*255,\s*\.055\)/)
  assert.doesNotMatch(css, /rgba\(12,\s*12,\s*14,\s*\.26\)/)
  assert.doesNotMatch(css, /rgba\(25,\s*18,\s*26,\s*\.52\)/)
  assert.doesNotMatch(css, /rgba\(15,\s*10,\s*17,\s*\.72\)/)
})

test('context menu opens as a reduced-motion-safe popover and does not replay on relayout', () => {
  const css = read('src', 'renderer', 'pages', 'context-menu.css')
  const js = read('src', 'renderer', 'pages', 'context-menu.js')
  assert.match(css, /\.menu-shell\[data-opening="true"\]/)
  assert.match(css, /scale\(\.96\)/)
  assert.match(css, /--open-motion:\s*220ms/)
  assert.match(css, /cubic-bezier\(\.16,\s*1,\s*\.3,\s*1\)/)
  assert.match(css, /prefers-reduced-motion:\s*reduce[\s\S]+--open-motion:\s*1ms linear/)
  assert.match(js, /state\.openSequence !== openSequence/)
  assert.match(js, /requestAnimationFrame/)
  assert.match(js, /shell\.animate\(/)
})
